DCNv2_criteo_x1_001_83a0b37e:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_002_41e9aba9:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_003_a7a94400:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_004_90c9061b:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_005_42006cf7:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_006_7689ac8e:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 9
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_007_b756ddcf:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_008_43e17586:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_009_84ea7863:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_010_f1474646:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_011_94e26da6:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_012_91c0e3fc:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 9
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_013_ba464c11:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_014_aafb1f76:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_015_e6fca0cc:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_016_187afecd:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_017_46a0ec22:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
DCNv2_criteo_x1_018_31555690:
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 9
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
