base_config: ../config/
base_expid: DCN_base
dataset_id: criteo_x4

dataset_config:
    criteo_x4:
        data_root: ../data/Criteo/
        data_format: csv
        train_data: ../data/Criteo/Criteo_x4/train.csv
        valid_data: ../data/Criteo/Criteo_x4/valid.csv
        test_data: ../data/Criteo/Criteo_x4/test.csv
        min_categr_count: 2
        feature_cols:
            - {name: [I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13],
               active: True, dtype: float, type: categorical, preprocess: convert_to_bucket, na_value: 0}
            - {name: [C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26],
               active: True, dtype: str, type: categorical, na_value: ""}
        label_col: {name: Label, dtype: float}

tuner_space:
    model_root: './Criteo/DCN_criteo_x4_002/'
    embedding_dim: 40
    learning_rate: 1.e-3
    crossing_layers: [7, 8, 9, 10]
    dnn_hidden_units: [[]]
    embedding_regularizer: [1.e-5, 5.e-5, 5.e-6]
    batch_size: 10000
    seed: 2019

