FFMv2_criteo_x1_001_ceec29b9:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFMv2_criteo_x1_002_33a2f554:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFMv2_criteo_x1_003_d39c0ceb:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFMv2_criteo_x1_004_9c79983e:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFMv2_criteo_x1_005_03afe185:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFMv2_criteo_x1_006_5fa7e386:
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 5
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFMv2
    model_id: FFMv2_base
    model_root: ./Criteo/FFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
