HFM_frappe_x1_001_3755ddc7:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_002_e78b5b22:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_003_a11ed302:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_004_0629aa62:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_005_8bdcd510:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_006_c7cac72b:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_007_1891ae2e:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_008_efe38430:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_009_15ea1cf8:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_010_7a01ba3f:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_011_38dbe863:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_012_1c8402b5:
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 1.0e-08
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
