DCN_frappe_x1_001_9ebaa245:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_002_3a511140:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_003_a694bc2f:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_004_dd926649:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_005_b755b0b0:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_006_9454bec4:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_007_d82ae748:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_008_87e1d58f:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_009_9894172f:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_010_25077dc3:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_011_16a88be9:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_frappe_x1_012_32f1600a:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Frappe/DCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
