SAM_criteo_x1_001_a78095e5:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_002_beb10d4e:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_003_beccfb68:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_004_5a717b85:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_005_e3e0f7c9:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_006_0a41bc23:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_007_3af58a16:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_008_b072a871:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_009_700ef215:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_010_e0d5ea31:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_011_1b186346:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_012_55e25f89:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_013_ecc032f2:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_014_94f97acd:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_015_be3a1569:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_016_288b2c8e:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_017_415e23ae:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_018_3dfd22d1:
    aggregation: concat
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_019_a49fc279:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_020_a8221c75:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_021_230a1e8b:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_022_3146b8a2:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_023_ce066906:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
SAM_criteo_x1_024_7483bbbd:
    aggregation: weighted_pooling
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    interaction_type: SAM3A
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: SAM
    model_id: SAM_base
    model_root: ./Criteo/SAM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 0
