xDeepFM_criteo_x4_001_d509bfbe:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64, 64]
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_002_2a55b766:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64]
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_003_5bcf1e69:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64, 64]
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_004_968a2d28:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64]
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
