AutoInt_microvideo1.7m_x1_006_12781deb:
    attention_dim: 256
    attention_layers: 3
    batch_norm: true
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    layer_norm: true
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./checkpoints/AutoInt_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_microvideo1.7m_x1_020_8371d5d9:
    attention_dim: 256
    attention_layers: 3
    batch_norm: false
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    layer_norm: true
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./checkpoints/AutoInt_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_microvideo1.7m_x1_021_4473d4bc:
    attention_dim: 256
    attention_layers: 3
    batch_norm: true
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    layer_norm: true
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./checkpoints/AutoInt_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    use_residual: true
    use_scale: false
    use_wide: false
    verbose: 1
