HFM_frappe_x1_001_725c6a90:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_002_cb2af38c:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_003_41dc17d2:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_004_390f06c2:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_005_b7a04355:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_006_0caf1c14:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_007_16d5515d:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
HFM_frappe_x1_008_6430a7ab:
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HFM
    model_id: HFM_base
    model_root: ./Frappe/HFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
