FM_kkbox_x1_001_b3912b07:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_id: FM_base
    model_root: ./KKBox/FM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FM_kkbox_x1_002_c55e9f15:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_id: FM_base
    model_root: ./KKBox/FM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FM_kkbox_x1_003_35c291f6:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_id: FM_base
    model_root: ./KKBox/FM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FM_kkbox_x1_004_4a0ac59e:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_id: FM_base
    model_root: ./KKBox/FM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.001
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
