xDeepFM_criteo_x4_001_5e0138b3:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_002_0a5b5311:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_003_444046bd:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39, 39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_004_5d2aa913:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_005_803ded93:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_006_5758b331:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100, 100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_007_b04f58d7:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_008_21cfc78c:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_009_efac2cb1:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200, 200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_010_c8abc738:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_011_b3aaef48:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_012_6102a622:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [39, 39, 39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_013_017aeddd:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_014_8be045bd:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_015_40bf68e7:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [100, 100, 100, 100]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_016_6383f518:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_017_9089e3c0:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_criteo_x4_018_32736b2f:
    batch_norm: false
    batch_size: 2000
    cin_layer_units: [200, 200, 200, 200]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/CIN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
