FGCNN_kkbox_x1_001_fa815919:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_002_0350570c:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_003_c10504c1:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_004_9509174a:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_005_d5377321:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_006_13dd9253:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_007_73d77714:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_008_f5b82bf6:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_009_f15f2fb1:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_010_1dcacca4:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_011_44473b9d:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_012_d5e0447e:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_013_1f3a1cad:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_014_48888fb8:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FGCNN_kkbox_x1_015_0d248c2f:
    batch_size: 2000
    channels: [14, 16, 18, 20]
    conv_activation: Tanh
    conv_batch_norm: true
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_activations: ReLU
    dnn_batch_norm: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    kernel_heights: [7, 7, 7, 7]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FGCNN
    model_id: FGCNN_base
    model_root: ./KKBox/FGCNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    save_best_only: true
    seed: 2019
    share_embedding: false
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
