DCN_criteo_x4_001_a967a157:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 7
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_002_eeeaa5c1:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 8
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_003_f0de7db8:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 9
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_004_d2d8893c:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 10
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_005_945f0ed5:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 7
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_006_b6a980d9:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 8
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_007_fea62582:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 9
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_008_2fc805ca:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 10
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_009_8f612f0a:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 7
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_010_7137c5ff:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 8
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_011_1482c0b0:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 9
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_012_89bb03a8:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 10
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 5.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
