FiGNN_criteo_x1_001_9ef5b8d3:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_002_3130fe0e:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_003_c6718583:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_004_8a16c64b:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_005_c5275d1f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_006_d61f1190:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_007_f8439cca:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_008_48fc6ffa:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_009_76b425da:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_010_10ad8661:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_011_62d25ffc:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_012_1bd89cf0:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_013_3f3f8ce0:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_014_e4b26896:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_015_236f1359:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_016_a1aa2cba:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_017_1d9857dd:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_criteo_x1_018_bd49211c:
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Criteo/FiGNN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
