DCNv2_avazu_x1_001_aec1d8d5:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_002_e72735a1:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_003_171b8c86:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_004_b9782b97:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_005_59c00971:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_006_1d38ba3c:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_007_a989d698:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_008_e00f7025:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_009_439768f5:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_010_59eaa503:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_011_e4cbb525:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_012_e0a8e337:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_013_e6bdb96d:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_014_541b0b75:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 7
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x1_015_9caa0f29:
    batch_norm: false
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x1/
    model_structure: crossnet_only
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 8
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
