DLRM_frappe_x1_002_227967b1:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.2
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_frappe_x1_004_1e84e17a:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.3
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_frappe_x1_006_216831a3:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.4
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_frappe_x1_008_c348e4a7:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.2
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_frappe_x1_010_4c75d69a:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.3
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_frappe_x1_012_e840fb94:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Frappe/DLRM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.4
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
