AOANet_taobaoad_x1_023_13c36c31:
    batch_norm: false
    batch_size: 4096
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 1
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: group_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 3
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
AOANet_taobaoad_x1_024_0b847c56:
    batch_norm: false
    batch_size: 4096
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 1
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: group_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 3
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
AOANet_taobaoad_x1_031_dfa10069:
    batch_norm: false
    batch_size: 4096
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 1
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: group_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 4
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
AOANet_taobaoad_x1_032_e234220e:
    batch_norm: false
    batch_size: 4096
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [512, 256, 128]
    early_stop_patience: 1
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: group_id
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
