APG_DeepFM_kuaivideo_x1_001_2c068851:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_002_844268b9:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [64, 32, 16]
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_003_ab9e42b1:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [32, 16, 8]
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_004_9ad67997:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_005_ab9e42b1:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_006_c46d6a33:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [64, 32, 16]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_007_5838d908:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [32, 16, 8]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_008_ebe12dd5:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_009_e30e15b4:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_010_a5167783:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [64, 32, 16]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_011_163f472e:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [32, 16, 8]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_kuaivideo_x1_012_94430ba9:
    batch_norm: false
    batch_size: 8192
    condition_features: null
    condition_mode: self-wise
    dataset_id: kuaivideo_x1_dc7a3035
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_emb}
    - {feature_encoder: layers.MaskedAveragePooling(), name: pos_items}
    - {feature_encoder: layers.MaskedAveragePooling(), name: neg_items}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: pos_items_emb
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: neg_items_emb
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_kuaivideo_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
