AFM_avazu_x4_3bbbc4c9_001_0087abd7:
    attention_dim: 16
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_002_b69fcf3c:
    attention_dim: 32
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_003_ff6d2665:
    attention_dim: 64
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_004_3194a7bf:
    attention_dim: 16
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_005_3b3981bc:
    attention_dim: 32
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_006_e393b28f:
    attention_dim: 64
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_007_28aeae11:
    attention_dim: 16
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_008_8bd19e2a:
    attention_dim: 32
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_009_496f5255:
    attention_dim: 64
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_010_af25d63f:
    attention_dim: 16
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_011_1017586e:
    attention_dim: 32
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_012_72985c82:
    attention_dim: 64
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_013_07911250:
    attention_dim: 16
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_014_e96ae56c:
    attention_dim: 32
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
AFM_avazu_x4_3bbbc4c9_015_22ba8d07:
    attention_dim: 64
    attention_dropout: [0, 0]
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFM
    model_id: AFM_base
    model_root: ./Avazu/AFM_avazu/min2/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_attention: true
    use_hdf5: true
    verbose: 1
    workers: 3
