DCN_avazu_x4_001_dc9d5714:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 1
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_002_fff8bacf:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 2
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_003_a1fc4a9f:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_004_af9d79fc:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 4
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_005_9fdba032:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 5
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_006_32b15b95:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 6
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_007_cb424ace:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 7
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_008_0eb619fb:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 1
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_009_4d5247d9:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 2
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_010_77edfca7:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 3
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_011_11f28e35:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 4
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_012_3534258c:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 5
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_013_b0d74e97:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 6
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_avazu_x4_014_0f6d60ee:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 7
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Avazu/DCN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
