xDeepFM_avazu_x4_001_79a6372e:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_002_73d43663:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_003_71f1fbd6:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_004_4dc419ed:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_005_7ef663e0:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_006_25698cfa:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [200, 200]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_007_9bc22a61:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_008_e76be77b:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_009_07456a3d:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_010_e953bdfe:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_011_210c9d17:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_012_d26fabec:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_013_184fbfd0:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_014_484a8c9e:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_015_9c219bae:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_016_09352230:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_017_09705802:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_018_71b27718:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_019_9214a52e:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_020_0d2b1bfd:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_021_c69e3990:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_022_5a5ec595:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_023_95c6298d:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_avazu_x4_024_135c16f2:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [50, 50, 50]
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
