HOFM_avazu_x1_001_b5759313:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
HOFM_avazu_x1_002_11ff3102:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
