FmFM_frappe_x1_001_d574c37e:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_frappe_x1_002_40901492:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_frappe_x1_003_ac8500dc:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_frappe_x1_004_2445bd6f:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_frappe_x1_005_1d1824dc:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_frappe_x1_006_d59e7cec:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Frappe/FmFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
