EDCN_criteo_x1_001_f4ae3285:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_002_6ec179a6:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_003_041f38d4:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_004_4023a363:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_005_8955f3d8:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 50
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_006_cd26f001:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 50
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_007_1dce4d8c:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_008_55bb2f23:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_009_6eb736c9:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_010_ea51c395:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_011_f8559dec:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 50
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_012_4db6ca4d:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 50
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
