LR_frappe_x1_001_ff730f43:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
LR_frappe_x1_002_7b222966:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
LR_frappe_x1_003_3bbcdcf0:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
LR_frappe_x1_004_7bcc5768:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
LR_frappe_x1_005_b4792618:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
LR_frappe_x1_006_cd451926:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Frappe/LR_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
