FwFM_avazu_x1_001_66fe1103:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FiLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_002_73bb79b1:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: LW
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_003_2c0af534:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_004_c0a5f00f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FiLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_005_bf2ba79d:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: LW
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_006_13fcb47f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_007_31ca38ae:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FiLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_008_09fa6b98:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: LW
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_009_b8820aaa:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_010_681818a5:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FiLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_011_382c9085:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: LW
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
FwFM_avazu_x1_012_01212a55:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
