DESTINE_movielenslatest_x1_001_51e815a5:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_002_d1c1d0c6:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_003_0ee2d5c3:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_004_5a28206c:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_005_f94e8d75:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_006_e1a3c936:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_007_81763549:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_008_36402bd0:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_009_caf33692:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_010_ac744c98:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_011_f64ca64d:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_012_2c4d5454:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_013_8c4bb06a:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_014_d4abc9db:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
DESTINE_movielenslatest_x1_015_f47dead1:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_movielenslatest_x1_016_e4b39e1f:
    att_dropout: 0.1
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Movielens/DESTINE_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: true
    verbose: 1
