FM_microvideo1.7m_x1_001_f3567ac6:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 0.005
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_002_0223e77e:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 0.001
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_003_ffc302aa:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_004_1ba9a35f:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 0.0005
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_005_b785531a:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_006_e6bf8b01:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_007_55f8bdc1:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_008_812e07a0:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_009_e3c785c4:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 5.0e-07
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_010_02f6d0b3:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_011_b9a2f4d5:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
FM_microvideo1.7m_x1_012_d994d13b:
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./checkpoints/FM_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    regularizer: 0
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
