DCN_criteo_x1_001_95179395:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 12
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_002_c3ca5973:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 13
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_003_115a3716:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 14
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_004_50565bd1:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 15
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
