MaskNet_movielenslatest_x1_001_909c948a:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_002_c8da86c1:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_003_2ad68440:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_004_e5bb864f:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_005_fc3b26ba:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_006_6d293a9c:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_007_217d0db3:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_008_87ee2843:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_009_e1c1399e:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_010_13a8d29c:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_011_4761a591:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_012_410aaf90:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_013_4d4ad251:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_014_35f1cef6:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 2
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_015_a1d10e1f:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_016_1dedb8da:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 4
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_017_02d6cc52:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
MaskNet_movielenslatest_x1_018_758ea5b1:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Movielens/MaskNet_movielenslatest_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 8
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
