xDeepFM_criteo_x4_003_c601dd6b:
    batch_norm: false
    batch_size: 5000
    cin_layer_units: [39, 39, 39, 39]
    dataset_id: criteo_x4_41e78b20
    debug: false
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-5)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_X4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
