AutoInt_avazu_x1_001_b52cf904:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_002_48b09cbf:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_avazu_x1_003_b68f9f53:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_004_1008f033:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_avazu_x1_005_73d0b026:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_006_3c4bb149:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_avazu_x1_007_e712e453:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_008_803a2557:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_avazu_x1_009_980c48b3:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_010_f0effa3f:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_avazu_x1_011_d5877b3a:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 0
AutoInt_avazu_x1_012_1bd35b53:
    attention_dim: 256
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
