APG_DeepFM_amazonelectronics_x1_001_daf845b0:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_002_387b911b:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [64, 32, 16]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_003_d5ff6cfd:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [32, 16, 8]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_004_e052c91f:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [32, 16, 8]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_005_10183a98:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_006_82656ace:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [64, 32, 16]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_007_5a43b9da:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [32, 16, 8]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_amazonelectronics_x1_008_cab1da7a:
    batch_norm: true
    batch_size: 1024
    condition_features: null
    condition_mode: self-wise
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    hypernet_config:
        dropout_rates: 0.1
        hidden_activations: relu
        hidden_units: []
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [16, 8, 4]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
