AOANet_criteo_x1_001_e19026ce:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_002_40a47fee:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_003_caefb24a:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_004_44adad28:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_005_faa15d7f:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_006_3962d1e3:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_007_18dd9e27:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 16
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AOANet_criteo_x1_008_a706ee66:
    batch_norm: true
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./Criteo/AOANet_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_interaction_layers: 1
    num_subspaces: 16
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
