AFN_frappe_x1_001_21c6b6b2:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_002_4f7dc98c:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_003_d7dfc93b:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_004_78d9245f:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_005_f8ac33c2:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_006_0a29f921:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_007_d848a22e:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_008_f15b0bf0:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_009_ea51eedc:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_010_d7637306:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_011_85381c76:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_012_f1b2cd03:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_013_ab145178:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_014_727caca8:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_015_2c4c6002:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_016_96f32d62:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_017_68556492:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_018_85accb7c:
    afn_activations: relu
    afn_dropout: 0.3
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
