HFM_criteo_x4_001_e623f3ba:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_002_300579d9:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_003_723b6428:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_004_a6cca8cb:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_005_c06c1202:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_006_2abdb8e2:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
