DeepFM_kkbox_x1_001_1422290b:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DeepFM_kkbox_x1_002_dcd509a3:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DeepFM_kkbox_x1_003_a3f02ad9:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DeepFM_kkbox_x1_004_a531f1f2:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DeepFM_kkbox_x1_005_32cb2ca8:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [5000, 5000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DeepFM_kkbox_x1_006_ccdbb724:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [5000, 5000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./KKBox/DeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
