FwFM_avazu_x4_003_9c0d0ea9:
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FiLV
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Avazu/FwFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
