FiGNN_avazu_x1_001_b8d1d210:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_002_070e26cc:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_003_bd9e15b7:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_004_fb43195a:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_005_9987365c:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_006_6edd1d43:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_007_7f5d909f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_008_cce31a6e:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_009_3ecdb50f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_010_89135551:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_011_634c72dd:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_012_27c58010:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_013_206e111f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_014_ec1a3641:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_015_9c5d8df1:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_016_bfb95212:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_017_0141a430:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_018_b6934577:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_019_02729762:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_020_29d34f5b:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_021_11b0e6e4:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_022_40b140b4:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_023_bf30bae5:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
FiGNN_avazu_x1_024_5efe2cca:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 0
