NFM_avazu_x1_001_06577b48:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_002_a476538d:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_003_48225479:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_004_017977f0:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_005_1fe17989:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_006_09188873:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_007_0412d1fc:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_008_733cb50c:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
NFM_avazu_x1_009_13bc08a9:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: NFM
    model_id: NFM_base
    model_root: ./Avazu/NFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
