AFN_criteo_x4_001_08150300:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_002_aec06d8f:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_003_f08fa895:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_004_ac20eea5:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_005_8b9efc2a:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_006_7e83fb04:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_007_673fe5fb:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_008_b7ae3c7c:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_009_242e44bf:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_010_bcbfa213:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_011_3d595e5c:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_012_d479cb4e:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1200
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_013_3258b224:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_014_9da1af57:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_015_a6181566:
    afn_activations: relu
    afn_dropout: 0.1
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
AFN_criteo_x4_016_645b2196:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [1000, 1000, 1000, 1000]
    batch_norm: true
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1500
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
