HOFM_avazu_x4_001_252b26d7:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 5]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_002_76651f2a:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 8]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_003_2ddaf394:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 10]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_004_6a5bc38a:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 5]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_005_d8c2ac6d:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 8]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_006_ff073d5e:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 10]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_007_0906a174:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 5]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_008_f9c5f283:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 8]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_009_fd35c08e:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 10]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_010_53fb9c4a:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 5]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_011_1ef7fef4:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 8]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_avazu_x4_012_515c681d:
    batch_size: 5000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: [40, 10]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Avazu/HOFM_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
