movielenslatest_x1_c9ce3754:
    data_format: csv
    data_root: ../data/MovielensLatest/
    feature_cols:
    -   active: true
        dtype: float
        name: [user_id, item_id, tag_id]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 1
    test_data: ../data/MovielensLatest/MovielensLatest_x1/test.csv
    train_data: ../data/MovielensLatest/MovielensLatest_x1/train.csv
    valid_data: ../data/MovielensLatest/MovielensLatest_x1/valid.csv
