FFM_movielenslatest_x1_001_79d12e82:
    batch_size: 4096
    dataset_id: movielenslatest_x1_c9ce3754
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFM
    model_id: FFM_base
    model_root: ./MovielensLatest/FFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFM_movielenslatest_x1_002_205b31b8:
    batch_size: 4096
    dataset_id: movielenslatest_x1_c9ce3754
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFM
    model_id: FFM_base
    model_root: ./MovielensLatest/FFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFM_movielenslatest_x1_003_43bf98ed:
    batch_size: 4096
    dataset_id: movielenslatest_x1_c9ce3754
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFM
    model_id: FFM_base
    model_root: ./MovielensLatest/FFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFM_movielenslatest_x1_004_fd0aeaf7:
    batch_size: 4096
    dataset_id: movielenslatest_x1_c9ce3754
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFM
    model_id: FFM_base
    model_root: ./MovielensLatest/FFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FFM_movielenslatest_x1_005_ff031f72:
    batch_size: 4096
    dataset_id: movielenslatest_x1_c9ce3754
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FFM
    model_id: FFM_base
    model_root: ./MovielensLatest/FFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
