PNN_criteo_x4_001_03f1791e:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_002_69a1df28:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_003_abbf0ecc:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_004_9dda7b42:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_005_a575e88a:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_006_5d20603f:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_007_a417d7e7:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_008_97692657:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_009_12067f58:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_010_2f077efd:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_011_a56b742f:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
PNN_criteo_x4_012_4612f862:
    batch_norm: false
    batch_size: 10000
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: PNN
    model_id: PNN_base
    model_root: ./Criteo/PNN_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
