FLEN_avazu_x4_001_61826db6:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_002_1f302ce3:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_003_1220d50b:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000, 2000]
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_004_7691b859:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_005_0a4586d1:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_006_1e50e8f0:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000, 2000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_007_4aa8c96d:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_008_92193e99:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000, 1000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FLEN_avazu_x4_009_54e3ad35:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_c9fb310a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [2000, 2000, 2000, 2000]
    embedding_dim: 16
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FLEN
    model_id: FLEN_base
    model_root: ./Avazu/FLEN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
