DeepFM_amazonelectronics_x1_001_686ce931:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_002_c8118109:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_003_7314827d:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_004_661cbfba:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_005_d1f0a8f9:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_006_23ea5fc6:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_007_b623b647:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_008_ed05641b:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_009_32d0b160:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_010_63c4a2b2:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_011_d408865a:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_012_bbe32034:
    batch_norm: false
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_013_5fea5c87:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_014_68eadb7e:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_015_fec24bd4:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DeepFM_amazonelectronics_x1_016_c91e813b:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./checkpoints/DeepFM_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
