DNN_amazonelectronics_x1_001_2068b004:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_002_ec4d65c0:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_003_5f863303:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_004_bbac9151:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_005_0a5f1f4b:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_006_1c0fd31b:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_007_41036f3f:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_008_b61bd584:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_009_81ffee36:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_010_3588a7a1:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_011_7c6d2a69:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_012_b5b13cc7:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_013_3fe56360:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_014_ff3547cf:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_015_3d191f5e:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
DNN_amazonelectronics_x1_016_2741918e:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_specs: null
    group_id: user_id
    hidden_activations: relu
    hidden_units: [1024, 512, 256]
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: DNN
    model_id: DNN_default
    model_root: ./checkpoints/DNN_amazonelectronics_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    verbose: 1
