AutoInt_movielenslatest_x1_001_8d3a2f25:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_002_84e5a47f:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_003_ca5f9626:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_004_4795ccb3:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_005_ee1b9cd4:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_006_c86f605a:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_007_c17c9cd8:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_008_170bd71f:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_009_d9ea8ec9:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_010_915c517d:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_011_0f28ff0e:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_012_4dcabc10:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_013_cf6af50c:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_014_e51dac6e:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_015_c781e576:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_016_59f25f45:
    attention_dim: 128
    attention_layers: 2
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_017_710a3934:
    attention_dim: 128
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_movielenslatest_x1_018_76811afc:
    attention_dim: 128
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Movielens/AutoInt_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 8
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
