HFM_kkbox_x1_001_27d9b307:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_002_e5ababeb:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_003_1510c184:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_004_4b7d8c86:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_005_647575d0:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_006_b549df4b:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 5.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_007_20a9c315:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
HFM_kkbox_x1_008_c9162e92:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./KKBox/HFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 0
    workers: 3
