InterHAt_avazu_x4_001_a838ca5b:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_002_307a6b7c:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_003_0e22590d:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_004_f44800d5:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_005_7682e4a5:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_006_fec73926:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_007_63b71da6:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_008_8e0967ec:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_009_34e90a84:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_010_fa912a4e:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_011_7ee7b9d1:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_012_0115dcbd:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 4
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_013_47fc7c38:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_014_fdb76ae7:
    attention_dim: 40
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_015_b8233839:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
InterHAt_avazu_x4_016_84214792:
    attention_dim: 80
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_dim: 500
    hidden_units: []
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: InterHAt
    model_id: InterHAt_base
    model_root: ./Avazu/InterHAt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    order: 5
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
