base_config: ../model_zoo/DMR/config/
base_expid: DMR_default
dataset_id: amazonelectronics_x1

dataset_config:
    amazonelectronics_x1:
        data_root: ../data/Amazon/
        data_format: csv
        train_data: ../data/Amazon/AmazonElectronics_x1/train.csv
        valid_data: ../data/Amazon/AmazonElectronics_x1/test.csv # no validation data split in original paper
        test_data: ../data/Amazon/AmazonElectronics_x1/test.csv
        min_categr_count: 1
        feature_cols:
            - {name: user_id, active: True, dtype: int, type: meta, remap: False}
            - {name: item_id, active: True, dtype: str, type: categorical}
            - {name: cate_id, active: True, dtype: str, type: categorical}
            - {name: item_history, active: True, dtype: str, type: sequence, splitter: ^, max_len: 100, padding: "post",
               feature_encoder: "layers.MaskedAveragePooling()", share_embedding: item_id}
            - {name: cate_history, active: True, dtype: str, type: sequence, splitter: ^, max_len: 100, padding: "post",
               feature_encoder: "layers.MaskedAveragePooling()", share_embedding: cate_id}
        label_col: {name: label, dtype: float}


tuner_space:
    model_root: './checkpoints/DMR_amazonelectronics_x1/'
    feature_specs: [[
            {name: item_history, feature_encoder: null},
            {name: cate_history, feature_encoder: null}
        ]]
    embedding_dim: 64
    dnn_hidden_units: [[1024, 512, 256]]
    target_field: [!!python/tuple [item_id, cate_id]]
    sequence_field: [!!python/tuple [item_history, cate_history]]
    dnn_activations: [ReLU, Dice]
    attention_hidden_units: [[512, 256]]
    attention_activation: Dice
    attention_dropout: 0.1
    use_pos_emb: [True, False]
    pos_emb_dim: [2, 8, 64]
    enable_sum_pooling: False
    enable_u2i_rel: [True, False]
    enable_i2i_rel: False
    embedding_regularizer: 5.e-3
    net_dropout: 0.1
    batch_norm: True
    bn_only_once: False
    learning_rate: 5.e-4
    batch_size: 1024
    seed: 20222023
    group_id: user_id
    metrics: [[gAUC, AUC, logloss]]
    monitor: gAUC

