WideDeep_avazu_x1_001_ce21e98b:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Avazu/WideDeep_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_avazu_x1_002_d8c146ac:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Avazu/WideDeep_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
