LR_kkbox_x1_001_578f312f:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_002_bbd58c8c:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_003_83c03a70:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-09
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_004_78410688:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-09
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_005_1b385558:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_006_a82bbe6d:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_007_cf0bd891:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_008_aab85bd2:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_009_e320c1c0:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_010_44026d81:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_011_1197a7dc:
    batch_size: 10000
    dataset_id: kkbox_x1_eb369ddd
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
LR_kkbox_x1_012_deae943b:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: LR
    model_id: LR_base
    model_root: ./KKBox/LR_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
