FiGNN_avazu_x4_001_4d4eb7da:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_002_c8515c76:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 9
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_003_77187973:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 10
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_004_f43f22b1:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_005_1127c6b0:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 9
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_006_c1870405:
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 10
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
