DCN_criteo_x4_001_964751c8:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 8
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/CrossNet_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_002_5d4b8850:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 9
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/CrossNet_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
DCN_criteo_x4_003_d8350574:
    batch_norm: false
    batch_size: 10000
    crossing_layers: 10
    dataset_id: criteo_x4_9ea3bdfc
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/CrossNet_criteo_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
