AFN_criteo_x1_001_888619b3:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [200]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 100
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_002_32798d82:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [200]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 100
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_003_788497bb:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [100]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 100
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_004_fccd853f:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [100]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 100
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_005_aa10b271:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [200]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 200
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_006_ba17992b:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [200]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 200
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_007_e8ac343d:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [100]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 200
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
AFN_criteo_x1_008_02747197:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [100]
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.1
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 200
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
