HFM_avazu_x4_001_e8fcbef4:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_002_b64275f6:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_003_4f0e5a76:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_004_22d2254f:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_005_8f97f15f:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_006_f641d58a:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_007_bbd9c821:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_008_c7c5322d:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_009_6e5b448d:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_010_cac778c5:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_011_d441733d:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_avazu_x4_012_37cda841:
    batch_norm: false
    batch_size: 5000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 1.0e-07
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Avazu/HFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: true
    use_hdf5: true
    verbose: 1
    workers: 3
