HOFM_movielenslatest_x1_001_2e77269c:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_movielenslatest_x1_002_aa2e5a5e:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_movielenslatest_x1_003_536dabcb:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 2.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_movielenslatest_x1_004_c58c682e:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 2.0e-06
    reuse_embedding: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_movielenslatest_x1_005_9c1936e7:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 8.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_movielenslatest_x1_006_d5bb72f2:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Movielens/HOFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 8.0e-07
    reuse_embedding: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
