HFM_criteo_x4_001_4e892904:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-4)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_002_bc5f3953:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-5)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_003_7b8b7c19:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-6)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_004_66651555:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-7)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_005_0e52c274:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-8)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_convolution
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_006_034528d0:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-4)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_007_e6fda6b9:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-5)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_008_4447a321:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-6)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_009_aae3becf:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-7)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
HFM_criteo_x4_010_bb624718:
    batch_norm: false
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: l2(1.e-8)
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [64, 64, 64]
    interaction_type: circular_correlation
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HFM
    model_id: HFM_base
    model_root: ./Criteo/HFM_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_dnn: false
    use_hdf5: true
    verbose: 1
    workers: 3
