FmFM_movielenslatest_x1_001_79806594:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_movielenslatest_x1_002_035dc563:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_movielenslatest_x1_003_28d4fd9f:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_movielenslatest_x1_004_560aab10:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_movielenslatest_x1_005_3ed01de7:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: vectorized
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FmFM_movielenslatest_x1_006_07297572:
    batch_size: 4096
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Movielens/FmFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
