EDCN_frappe_x1_001_9bb72f95:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_002_c3fe7259:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_003_29c3c55a:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_004_04a98b41:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_005_bced92d9:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_006_5e8b9617:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_007_afec4bef:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_008_e25cfd2e:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_009_9aceb8cf:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_010_a1a1d33e:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_011_d6b76b2d:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_frappe_x1_012_c87c0a5d:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Frappe/EDCN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 20
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
