FiGNN_frappe_x1_001_fe1e4bff:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 15
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
FiGNN_frappe_x1_002_2701f487:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
FiGNN_frappe_x1_003_57243619:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 17
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
FiGNN_frappe_x1_004_32f52aaa:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 18
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
FiGNN_frappe_x1_005_6109701a:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 19
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
FiGNN_frappe_x1_006_cbc083c1:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 20
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Frappe/FiGNN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
