FiGNN_criteo_x4_001_e609c0de:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_002_8e5efc86:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_003_a6823edc:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_criteo_x4_004_c912df41:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_criteo_x4_005_033c41f1:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_006_b38b95e8:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_007_e9177ddd:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_criteo_x4_008_f8edf8c8:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_criteo_x4_009_4c9c2119:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_010_a2734154:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_criteo_x4_011_abbb043d:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_criteo_x4_012_96859c28:
    batch_size: 5000
    dataset_id: criteo_x4_41e78b20
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_criteo_x4
    model_root: ./Criteo/FiGNN_criteo_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
