xDeepFM_movielenslatest_x1_001_0de9d14a:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32, 32]
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Movielens/xDeepFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_movielenslatest_x1_002_b13b4600:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64, 64, 64]
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Movielens/xDeepFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_movielenslatest_x1_003_0f21220c:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64, 64, 64, 64]
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Movielens/xDeepFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_movielenslatest_x1_004_af1ff7e9:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [128, 128, 128, 128]
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Movielens/xDeepFM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
