xDeepFM_kkbox_x1_001_8c750487:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_002_946a7ed9:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_003_a86d7953:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [78, 78]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_004_ad25db8a:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [78, 78, 78]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_005_a0785118:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [128, 128, 128]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_007_67419ba8:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_008_b23e94fd:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_010_16d427c4:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [78, 78, 78]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_011_af65cddb:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [128, 128, 128]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_012_90f1b5fb:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [128, 128]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_013_b16ed181:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_014_4c5d670e:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [64, 64, 64]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_017_d6653c66:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [128, 128, 128]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: []
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/CIN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
