DESTINE_avazu_x1_001_787ca977:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_002_e1b666bc:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_003_f9e1c55c:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_004_15f08749:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_005_22d31b9f:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_006_d530f867:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_007_5c4962e2:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_008_e34b318e:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_009_f49d04ab:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_010_1c186061:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_011_386a123d:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_012_2ecaf4c4:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_013_ec50b715:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_014_f5114de3:
    att_dropout: 0
    attention_dim: 128
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_015_1965aed2:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 4
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
DESTINE_avazu_x1_016_61d63533:
    att_dropout: 0
    attention_dim: 64
    attention_layers: 3
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DESTINE
    model_id: DESTINE_base
    model_root: ./Avazu/DESTINE_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    relu_before_att: false
    residual_mode: each_layer
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_scale: true
    use_wide: false
    verbose: 1
