LR_avazu_x1_001_6b530e60:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_002_e2ed54fc:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_003_538dde28:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_004_f29f7195:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_005_f1a80002:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_006_e2f4619f:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_007_c7701820:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
LR_avazu_x1_008_ae8e4124:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: LR
    model_id: LR_base
    model_root: ./Avazu/LR_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-08
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
