FiGNN_avazu_x4_001_cb05e01b:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_002_1690d8d2:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_003_505e7795:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_004_0f95f166:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_005_918ee532:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 10
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_006_1243c7b7:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 5
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_007_2d25cf8b:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 6
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_008_ccf81dae:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 7
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_009_ecabf370:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 8
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_avazu_x4_010_95f88706:
    batch_size: 2000
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 10
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./Avazu/FiGNN_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
