HOFM_frappe_x1_001_e4f4ae23:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Frappe/HOFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_frappe_x1_002_adbdec64:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Frappe/HOFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_frappe_x1_003_64d2d04e:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Frappe/HOFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_frappe_x1_004_cead4fc1:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Frappe/HOFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
HOFM_frappe_x1_005_d4b3089e:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 200
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: HOFM
    model_id: HOFM_base
    model_root: ./Frappe/HOFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-07
    reuse_embedding: false
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
