APG_DeepFM_taobaoad_x1_001_f9c13c6b:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_taobaoad_x1_002_d01b9650:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: null
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_taobaoad_x1_003_d01b9650:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [128, 64, 32]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_taobaoad_x1_004_96c132ac:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [128, 64, 32]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_taobaoad_x1_005_5f3c9dae:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: null
    pickle_feature_encoder: true
    rank_k: [256, 128, 64]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
APG_DeepFM_taobaoad_x1_006_35d5ea40:
    batch_norm: false
    batch_size: 4096
    condition_features: null
    condition_mode: self-wise
    dataset_id: taobaoad_x1_2753db8a
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 32
    embedding_regularizer: 5.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    generate_bias: true
    group_id: group_id
    hidden_activations: relu
    hidden_units: [512, 256, 128]
    hypernet_config:
        dropout_rates: 0
        hidden_activations: relu
        hidden_units: [512]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: APG_DeepFM
    model_root: ./checkpoints/APG_DeepFM_taobaoad_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    new_condition_emb: false
    num_workers: 3
    optimizer: adam
    overparam_p: [128, 64, 32]
    pickle_feature_encoder: true
    rank_k: [256, 128, 64]
    save_best_only: true
    seed: 20222023
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
