WideDeep_criteo_x1_001_dddca956:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_002_b524a942:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_003_693f6448:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_004_c8052b05:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_005_0d746359:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_006_7fa71e5b:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_007_0ee9095c:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_008_e7a35f4f:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_009_cc1b1340:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_010_3a06c5bc:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_011_13362151:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_012_68d08a0b:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_013_2decf052:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_014_dcc49875:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_015_3780c133:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
WideDeep_criteo_x1_016_4b0d5cc8:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: WideDeep
    model_id: WideDeep_base
    model_root: ./Criteo/WideDeep_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
