DCNv2_avazu_x4_001_5e30b8d4:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_002_1a82ae64:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_003_09b69ca2:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_004_1a2da6a6:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_005_0f059aed:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_006_42ea03cb:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_007_6eb830fd:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_008_5a1073ef:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 6
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_009_5084a41d:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_010_ef8256f1:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_011_19794dc6:
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
DCNv2_avazu_x4_012_b77e203c:
    batch_norm: true
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 1.0e-09
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 0
