DLRM_movielenslatest_x1_001_e8b93aa9:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Movielens/DLRM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.3
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_movielenslatest_x1_002_333e0a39:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Movielens/DLRM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.2
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_movielenslatest_x1_003_96dc50a9:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Movielens/DLRM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.3
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
DLRM_movielenslatest_x1_004_0b7acbe0:
    batch_norm: true
    batch_size: 4096
    bottom_mlp_activations: ReLU
    bottom_mlp_dropout: 0
    bottom_mlp_units: null
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    interaction_op: cat
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DLRM
    model_id: DLRM_base
    model_root: ./Movielens/DLRM_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    top_mlp_activations: ReLU
    top_mlp_dropout: 0.2
    top_mlp_units: [400, 400, 400]
    use_hdf5: true
    verbose: 1
