AOANet_microvideo1.7m_x1_046_d6274226:
    batch_norm: true
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_interaction_layers: 4
    num_subspaces: 16
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
AOANet_microvideo1.7m_x1_047_8c365b47:
    batch_norm: true
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_interaction_layers: 4
    num_subspaces: 16
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
AOANet_microvideo1.7m_x1_048_7fe25eda:
    batch_norm: true
    batch_size: 2048
    dataset_id: microvideo1.7m_x1_0d855fe6
    debug_mode: false
    dnn_hidden_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_interval: 1
    feature_specs:
    - {feature_encoder: 'nn.Linear(64, 64, bias=False)', name: item_id}
    -   feature_encoder: [layers.MaskedAveragePooling(), 'nn.Linear(64, 64, bias=False)']
        name: clicked_items
    - {feature_encoder: layers.MaskedAveragePooling(), name: clicked_categories}
    group_id: group_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [gAUC, AUC, logloss]
    model: AOANet
    model_id: AOANet_base
    model_root: ./checkpoints/AOANet_microvideo1.7m_x1/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_interaction_layers: 4
    num_subspaces: 16
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    task: binary_classification
    verbose: 1
