AutoInt_criteo_x1_001_0766c4e2:
    attention_dim: 256
    attention_layers: 5
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_002_17175f63:
    attention_dim: 256
    attention_layers: 5
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_003_2e1ac60d:
    attention_dim: 256
    attention_layers: 5
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_004_1b6439e7:
    attention_dim: 256
    attention_layers: 5
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_005_bb5d541c:
    attention_dim: 256
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_006_26c4ca99:
    attention_dim: 256
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_007_bc2643db:
    attention_dim: 256
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_008_15ab2e52:
    attention_dim: 256
    attention_layers: 4
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_009_e0cee734:
    attention_dim: 256
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_010_908e4976:
    attention_dim: 256
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_011_9f4f7bd0:
    attention_dim: 256
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 0
AutoInt_criteo_x1_012_e71394ec:
    attention_dim: 256
    attention_layers: 3
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Criteo/AutoInt_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 0
