FiBiNET_avazu_x4_001_e96e8342:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_all
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_002_d7bc4182:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_each
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_003_dc867dda:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_interaction
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_004_a636b915:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_all
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_005_31c0eccb:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_each
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_006_3cfdaa04:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_interaction
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_007_3859283b:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_all
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_008_b845e50d:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_each
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_009_bb3ef68b:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_interaction
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_010_50767864:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_all
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_011_2b08e359:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_each
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_012_fe1312f5:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_interaction
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_013_44893da7:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_all
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_014_dbfe730e:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_each
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
FiBiNET_avazu_x4_015_4abf0123:
    batch_norm: false
    batch_size: 10000
    bilinear_type: field_interaction
    dataset_id: avazu_x4_d102865a
    debug: false
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [1000, 1000, 1000, 1000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiBiNET
    model_id: FiBiNET_base
    model_root: ./Avazu/FiBiNET_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 3
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
