EDCN_movielenslatest_x1_001_721b0f44:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_002_596a6663:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_003_b42bf948:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_004_d82b129e:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_005_d2817da2:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_006_484f3fbd:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_007_619f0f7f:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_008_4f6fdebd:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 1
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_009_120b6c91:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_010_675c3e00:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_011_66510aab:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
EDCN_movielenslatest_x1_012_ae994eb9:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: false
    verbose: 1
