FwFM_frappe_x1_001_b8db9675:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Frappe/FwFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FwFM_frappe_x1_002_e1ce8c57:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Frappe/FwFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FwFM_frappe_x1_003_3b74c1d9:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Frappe/FwFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-07
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FwFM_frappe_x1_004_e7187911:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Frappe/FwFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FwFM_frappe_x1_005_95cf3ccd:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    linear_type: FeLV
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FwFM
    model_id: FwFM_base
    model_root: ./Frappe/FwFM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
