xDeepFM_avazu_x1_001_8bca7f04:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_002_02db9203:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_003_7f3fed32:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_004_b9b28555:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_005_8eafedf1:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_006_9121d13d:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_007_acd9c8c1:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_008_18fbb984:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_009_85c55cf6:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_010_cd26f835:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_011_f89e9edc:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
xDeepFM_avazu_x1_012_7f5af435:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [64, 64, 64, 64]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
