base_config: ../model_zoo/APG/config/
base_expid: APG_DeepFM
dataset_id: taobaoad_x1

dataset_config:
    taobaoad_x1:
        data_root: ../data/Taobao/
        data_format: csv
        train_data: ../data/Taobao/TaobaoAd_x1/train.csv
        valid_data: ../data/Taobao/TaobaoAd_x1/test.csv
        test_data: ../data/Taobao/TaobaoAd_x1/test.csv
        min_categr_count: 10
        feature_cols:
            - {name: "group_id", active: True, dtype: int, type: meta, preprocess: "copy_from(userid)", remap: False}
            - {name: ["userid","cms_segid","cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level",
                      "occupation","new_user_class_level","adgroup_id","cate_id","campaign_id","customer","brand","pid","btag"],
                      active: True, dtype: str, type: categorical}
            - {name: price, active: True, dtype: float, type: numeric}
            - {name: cate_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
               share_embedding: cate_id}
            - {name: brand_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
               share_embedding: brand}
            - {name: btag_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
               share_embedding: btag}
        label_col: {name: clk, dtype: float}


tuner_space:
    model_root: './checkpoints/APG_DeepFM_taobaoad_x1/'
    embedding_dim: 32
    hidden_units: [[512, 256, 128]]
    embedding_regularizer: 5.e-6
    net_dropout: 0
    batch_norm: False
    hypernet_config:
        hidden_units: [512]
        hidden_activations: relu
        dropout_rates: 0
    condition_features: null
    condition_mode: "self-wise"
    rank_k: [null, [128, 64, 32], [256, 128, 64]]
    overparam_p: [null, [128, 64, 32]]
    new_condition_emb: False
    generate_bias: True
    learning_rate: 1.e-3
    batch_size: 4096
    seed: 20222023
    group_id: group_id
    metrics: [[gAUC, AUC, logloss]]
    monitor: {"gAUC": 1, "AUC": 1}
  
