AFN_frappe_x1_001_04123f66:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_002_960e46af:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_003_93ab5de3:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_004_d2ea60c3:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_005_b5ba67bd:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_006_3d910675:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_007_9b69e9d9:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_008_d66baeaf:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_009_25a4a087:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_010_c70dc92b:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_011_45137d7f:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_012_d4a79cd3:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.0001
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_013_dd3a9399:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_014_5c2a6c4c:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_015_2aed3c73:
    afn_activations: relu
    afn_dropout: 0.2
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_016_1d25669b:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.2
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_017_59422700:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.3
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_frappe_x1_018_3b3b7ec5:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [400]
    batch_norm: false
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_dropout: 0.4
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: true
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 1000
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Frappe/AFN_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
