AFN_criteo_x1_001_24c2fde4:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 400
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_criteo_x1_002_d1191676:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 400
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_criteo_x1_003_0d39db36:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_criteo_x1_004_d00a01ec:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 600
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_criteo_x1_005_23f3dc2f:
    afn_activations: relu
    afn_dropout: 0.4
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
AFN_criteo_x1_006_58e0aa6b:
    afn_activations: relu
    afn_dropout: 0.5
    afn_hidden_units: [800]
    batch_norm: false
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_dropout: 0
    dnn_hidden_units: []
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    ensemble_dnn: false
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    logarithmic_neurons: 800
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AFN
    model_id: AFN_base
    model_root: ./Criteo/AFN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
