FM_frappe_x1_001_6234f1e3:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./Frappe/FM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
FM_frappe_x1_002_b2481e92:
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./Frappe/FM_frappe_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-05
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
