name: jupyter-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    # Install dependencies and build the book
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - run: |
        cd docs
        pip install -r requirements.txt
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: Deploy github-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: openbenchmark/openbenchmark.github.io
        publish_branch: main
        publish_dir: ./docs/_build/html
        exclude_assets: '_sources'
        destination_dir: BARS
