name: jupyter-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    # Install dependencies
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - run: pip install jupyter-book==0.15.1, docutils==0.17.1

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: Deploy github-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./_build/html
        exclude_assets: '_sources'
        external_repository: openbenchmark/openbenchmark.github.io
        publish_branch: main
        destination_dir: BARS
