AutoInt_avazu_x4_003_cc789c7e:
    attention_dim: 64
    attention_layers: 3
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_d102865a
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000, 1000]
    embedding_dim: 40
    embedding_dropout: 0
    embedding_regularizer: 1.0e-08
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Avazu/AutoInt_avazu_x4_002/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_heads: 1
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: false
    verbose: 1
    workers: 3
